reearth/reearth-web

src/components/molecules/Common/AssetModal/index.tsx
src/components/molecules/Common/plugin/builtin/widgets/menu.tsx

Bug fix:
- menu widget's item functionality wasn't working (link and flight)
Change:
- Asset modal now shows newest items at the top by default

fix: menu widget & change asset modal default order

---

src/components/atoms/TreeView/Item.tsx
src/components/atoms/TreeView/hooks.ts
src/components/atoms/TreeView/types.ts
src/components/molecules/EarthEditor/LayerTreeViewItem/Layer.tsx
src/components/molecules/EarthEditor/LayerTreeViewItem/index.tsx

- fix bug where deselecting a child layer would close the folder
-  update to show indicator beside parent when child is selected

fix: layer panel bug

---

src/components/pages/TopPage/hooks.ts

If the `me` query returns `null`. The screen becomes black and the user couldn't do anything.
Without the valid query result, force the user to log out.

fix: force logout when me query returns null

---

src/components/molecules/Common/plugin/builtin/widgets/menu.tsx

When the menu has been opened the style should be kept well
I made the menu min-width of 200px
but if the button is wider the menu will take the whole width (as shown in the screenshots)

fix: menu button width

---

src/components/molecules/Common/AssetModal/AssetContainer/hooks.ts
src/components/molecules/Common/AssetModal/AssetContainer/index.tsx
src/components/molecules/Common/AssetModal/AssetDeleteModal/index.tsx
src/components/molecules/Settings/Workspace/Asset/AssetDeleteModal/index.tsx
src/components/organisms/Dashboard/hooks.ts
src/components/organisms/Settings/ProjectList/hooks.ts
src/components/organisms/Settings/ProjectList/index.tsx

- add a delete assets modal in assets setting page
- fix project page no data bug
- fix no create new asset bug
@Basel-Issmail @KaWaite

feat: add  delete assets confirm modal and fix bugs

---

src/components/molecules/Common/plugin/builtin/primitives/photooverlay.tsx
yarn.lock

Unpredictable and weird camera/flight behaviour with photo overlays in the storytelling feature. Camera will sometimes shoot far away from the earth before settling into the correct position. Sometimes the flight to the next photo overlay will stop abruptly and return to the prev position. Then, on next story the flight will final move to the 2nd(now previous) position.
Add a condition to the photo overlay so that it will not return to previous position if NOT selected still.
Tested storytelling with photo overlay stories, all defaults.
Tested storytelling with photo overlay stories, first, then second, then third photo overlay story getting set camera positions.
Tested storytelling with photo overlay stories with both photo overlays AND storytelling setting camera.

fix: flight issue with photo overlay in Storytelling feature

---

src/components/atoms/Icon/index.tsx
src/components/atoms/Markdown/index.tsx
src/components/molecules/Common/plugin/builtin/widgets/MenuButton.tsx
src/components/molecules/Common/plugin/builtin/widgets/menu.stories.tsx
src/components/molecules/Common/plugin/builtin/widgets/menu.tsx
yarn.lock

Fixes:
- Icons don't be displayed
- Camera doesn't fly once flight  button is clicked
- Warning from Markdown component
- "Undefined" page will open when url property is empty and button os clicked
- When menu text is CJK only, it breaks the line

fix: menu widget bugs

---

src/components/organisms/Settings/Workspace/Asset/hooks.ts

Asset modal shows assets by default newest first, but assets in settings didn't.
reverse default order of assets in settings page

fix: change order of assets in settings (newest first)

---

src/components/molecules/Common/plugin/builtin/widgets/storytelling.tsx

Just a bandaid fix as a better fix is coming with the reworked plugin system!

fix: show layers in storytelling without names

---

src/components/organisms/Settings/Account/index.tsx

Dropdown in settings page, always selects a wrong default value after refreshing the page.
Load component when `me` value is available
1- Go to Account page
2- Set language to Japanese, or set theme to light theme
3- Refresh page
4- Click on edit dropdown value
5- Right value appears
https://user-images.githubusercontent.com/78056580/127628724-f291e6e4-e9a9-45bd-8b17-e04beeb13b4c.mp4
fixes https://github.com/reearth/reearth/issues/88

fix: account dropdowns show wrong values

---

src/@types/index.d.ts
src/components/atoms/Icon/index.stories.tsx
src/components/atoms/Icon/index.tsx

- Bounding box of Icon component has been fixed
- Now `<Icon src="<svg>...</svg>" />` works again
- Support style prop of Icon component

fix: icon background

---

package.json
src/app.tsx
src/components/pages/GraphQLPlayground/index.tsx
yarn.lock

reearth/reearth#89
Add GraphiQL page to enable to debug GraphQL
- URL: `/graphql`
- An access token will be automatically injected to headers
- Not available on production build
- `graphql-playground-react` has a dependency to Redux
- Error were occurred when I tried `graphql-playground-react` and it did not work
- GitHub adopts GraphiQL on the GraphQL playground page for GitHub GraphQL API

feat: graphiql page

---

src/components/molecules/EarthEditor/OutlinePane/hooks.tsx
src/components/molecules/EarthEditor/OutlinePane/index.stories.tsx
src/components/molecules/EarthEditor/OutlinePane/index.tsx
src/components/molecules/EarthEditor/PropertyPane/PropertyItem/index.stories.tsx
src/components/molecules/EarthEditor/PropertyPane/PropertyItem/index.tsx
src/components/organisms/EarthEditor/OutlinePane/hooks.tsx
src/components/organisms/EarthEditor/PropertyPane/convert.ts
src/components/organisms/EarthEditor/PropertyPane/hooks-queries.ts
src/components/organisms/EarthEditor/PropertyPane/hooks.ts
src/components/organisms/EarthEditor/PropertyPane/queries.ts
src/gql/fragments/property.ts
src/gql/graphql-client-api.tsx
src/gql/graphql.schema.json
src/state/index.ts

Follow https://github.com/reearth/reearth-backend/pull/43 's change:
- Replace deprecated fields in queries
- Change input of widget mutation
No UI changes
Manually tested

refactor: replace deprecated gql fields, pass widgetId to widget mutations

---

src/components/atoms/TextBox/index.tsx
src/components/molecules/Settings/Account/AccountSection/index.tsx
src/components/molecules/Settings/Account/PasswordModal/index.tsx
src/components/molecules/Settings/Project/EditableItem/index.tsx

Users were unable to change their password
The frontend's handling of updating the password was wrong. We were sending to the backend the old password and the new password confirmation. We should send the new password and confirmation only. 
Anyways the user doesn't need to input their old password bc they are authenticated. 
Also found a warning in AccountSection so cleaned up that component.
Added type prop to TextBox so we could use it for passwords and hide the inputted characters.
- Changed my own password on local multiple times

fix: password updating

---

src/components/organisms/Settings/Account/hooks.ts

Some parts of the UI wouldn't update after the language was changed. In particular the right panel when navigating from the Account Settings back to the Earth Editor.
Since the right panel's fields come from the backend and are stored in cache, after language is changed the apollo cache is reset so any possible translations coming from the backend will be fetched again with the new language.

fix: language change not updating

---

src/components/organisms/Dashboard/hooks.ts
src/components/organisms/EarthEditor/Header/hooks.ts
src/components/organisms/Settings/SettingPage/hooks.ts
src/components/organisms/Settings/Workspace/hooks.ts

Had an issue where a personal workspace showed the members section when it shouldn't be rendered (personal workspace's only member is you, so no need).
- Cleanup code around updating team state
- fix where personal workspace page showed members section
- In the Dashboard, change to different workspace from header. Change back to personal workspace. Select "Manage workspaces". Click on workspace from left navigation. Should not show members section.

fix: showing members section for personal workspace

---

src/components/atoms/Plugin/IFrame/hooks.ts
src/components/atoms/Plugin/IFrame/index.stories.tsx
src/components/atoms/Plugin/IFrame/index.tsx
src/components/atoms/Plugin/index.stories.tsx
src/components/atoms/Plugin/index.tsx
src/components/molecules/Visualizer/Plugin/hooks.ts
src/components/molecules/Visualizer/Plugin/index.tsx
src/components/molecules/Visualizer/Plugin/types.ts
src/components/molecules/Visualizer/Widget/Button/index.stories.tsx
src/components/molecules/Visualizer/Widget/Button/index.tsx
src/components/molecules/Visualizer/Widget/Menu/index.stories.tsx
src/components/molecules/Visualizer/Widget/Menu/index.tsx
src/components/molecules/Visualizer/Widget/SplashScreen/index.stories.tsx
src/components/molecules/Visualizer/Widget/SplashScreen/index.tsx
src/components/molecules/Visualizer/Widget/Storytelling/index.stories.tsx
src/components/molecules/Visualizer/Widget/Storytelling/index.tsx
src/components/molecules/Visualizer/Widget/index.tsx
src/components/molecules/Visualizer/WidgetAlignSystem/hooks.ts

```ts
type Widget {
extended: boolean;
}
```
↓
```ts
type Widget {
extended?: { horizontally: boolean; vertically: boolean; };
}
```
Manually

feat: enhance extended field of widget in plugin API

---

src/components/molecules/Visualizer/Engine/Cesium/hooks.ts
src/components/molecules/Visualizer/Engine/Cesium/useEngineRef.ts
src/components/molecules/Visualizer/Widget/Storytelling/hooks.ts

Fix:
- Camera won't fly when selecting photo overlay and then selecting next story with storytelling widget
- Camera flight will sometimes stop

fix: camera flight bugs

---

src/components/molecules/Visualizer/Infobox/Frame/index.tsx

If infobox had no content the icons wouldn't show when minimized.
Before:
After:

fix: minimized infobox's icons not showing

---

src/components/atoms/Markdown/index.tsx

fix: markdown background color is not transparent

---

.gitignore
webpack.config.js

`.env` is poor to represent nested and complrex objects, so now `reearth-config.json` will be automatically loaded if it exists on `yarn start`.

chore: load local reearth-config.json for debugging

---

src/components/molecules/Visualizer/WidgetAlignSystem/MobileZone.tsx
src/components/molecules/Visualizer/WidgetAlignSystem/index.tsx
src/components/organisms/EarthEditor/CanvasArea/convert.ts
src/components/organisms/Published/hooks.ts

Fixes a few things:
-  inner section's widgets were disappearing if no widgets in center section, so fixed that
-  If no widgets in middle section (including inner), default to left
- updated published project's widget filtering to return undefined when empty

fix: widget align system issues

---

src/components/molecules/Visualizer/WidgetAlignSystem/MobileZone.tsx

Testing found that on some mobile browsers (iOS's Chrome and Safari) the right arrow icon in the navigation wouldn't align correctly to the right (end). Seems like this has to do with the "start", "end", etc simplified standard being set by W3C not being widely compatible yet within the CSS flex context.
NOTE: This bug can't be seen in desktop browsers (even using dev tools). Needs to be merged to check on actual devices.
Before:
After:

fix: mobile align system's icon in some browsers

---

src/components/molecules/Visualizer/Engine/Cesium/hooks.ts
src/components/molecules/Visualizer/Engine/Cesium/index.tsx
src/components/molecules/Visualizer/Engine/Cesium/terrain.ts
src/components/molecules/Visualizer/Engine/index.tsx

Enhance terrain feature:
- Support selecting terrain type
- Cesium World Terrain, ArcGIS Terrain
- Default is cesium
- Support terrain exaggeration
Backend is already implemented by https://github.com/reearth/reearth-backend/commit/8693b4833399c06958bab2c553f19bd4e0341603 and https://github.com/reearth/reearth-backend/commit/5e3d253ea63f2aaa356d7af528fbb8556d4b40d8

feat: enhance terrain feature (type selection, exaggeration)

---

src/components/molecules/Visualizer/Engine/Cesium/Cluster.tsx

Labels aren't displayed correctly, because labels and billboard are on the same level as billboards
Added a small `eyeOffset` to the label so it renders in front of the billboard
Solution according to [Label positioned behind billboard/point](https://groups.google.com/g/cesium-dev/c/cbypD-8kaSc)
Old:
New:

fix: position label in front of billboard

---

src/components/molecules/Visualizer/Engine/Cesium/hooks.ts
src/components/molecules/Visualizer/Engine/Cesium/index.tsx

- Storytelling is not reaching it's destination markers on published projects.
- Removed the `throttle` code, and got back the old value of `percentageChanged`.
Tested 3 things:
- storytelling 
- stutter camera
- camera limiter

fix: storytelling widget camera flight

---

src/components/atoms/Plugin/IFrame/hooks.ts
src/components/atoms/Plugin/IFrame/index.tsx
src/components/atoms/Plugin/index.tsx
src/components/molecules/Visualizer/Block/index.tsx
src/components/molecules/Visualizer/Plugin/index.tsx

Support selecting blocks with plugins by clicking

fix: enable to select blocks of plugins

---

src/components/atoms/ContentPicker/index.tsx

- Removed `height` property from the parent.

fix: the style of infobox block dropdown list is broken

---

src/components/molecules/EarthEditor/PropertyPane/PropertyItem/index.tsx

Deleting custom blocks
- Removed name checking condition
- Did not add any features
- Create custom block
- Delete custom blocks
-  Delete infobox
- Delete builtin blocks
- Code change

fix: plugin blocks cannot be deleted

---

src/components/organisms/Dashboard/queries.ts
src/gql/graphql-client-api.tsx

- In the workspace setting page, the `New member` button disappear
Updated the `me` mutation to include member roles.
Follow steps described [here](https://github.com/reearth/reearth/issues/205)

fix: new member button disappear

---

src/components/organisms/Published/hooks.ts
src/components/organisms/Published/index.tsx
src/components/organisms/Published/types.ts

fix https://github.com/reearth/reearth/issues/212

fix: support tree-structured layers and tags in published pages

---

src/components/atoms/Plugin/IFrame/hooks.ts
src/components/atoms/Plugin/IFrame/index.tsx
src/components/atoms/Plugin/hooks.ts
src/components/atoms/Plugin/index.stories.tsx
src/components/atoms/Plugin/index.tsx
src/components/molecules/Visualizer/Plugin/api.ts
src/components/molecules/Visualizer/Plugin/hooks.ts
src/components/molecules/Visualizer/Plugin/index.tsx
src/components/molecules/Visualizer/Plugin/types.ts
src/components/molecules/Visualizer/Widget/Storytelling/index.tsx
src/components/molecules/Visualizer/Widget/index.tsx
src/components/molecules/Visualizer/WidgetAlignSystem/Area.tsx

```diff
type PluginAPIUI = {
// ...
render: (html: string, options: {
visible?: boolean;
+   width?: number | string;
+   height?: number | string;
+   extended?: boolean;
}) => void;
+ resize: (
+   width: number | string | undefined,
+   height: number | string | undefined,
+   extended: boolean | undefined
+ ) => void;
};
```

feat: add a plugin API to resize iframe by plugins

---

src/components/molecules/Visualizer/Infobox/Frame/index.tsx
src/components/molecules/Visualizer/Infobox/index.tsx
src/components/molecules/Visualizer/Widget/Button/MenuButton.tsx
src/components/molecules/Visualizer/Widget/Button/index.tsx
src/components/molecules/Visualizer/WidgetAlignSystem/Zone.tsx
src/components/molecules/Visualizer/hooks.ts
src/components/molecules/Visualizer/index.tsx

Had problem with the text inside button widgets gettings squished when width of viewer wasn't wide enough to safely contain multiple widgets side by side.
Updated the widget align system so that it will wrap its widgets if not enough space. This created a little issue with the Button widgets, so needed to update their min-sizes.
Also, as requested by @lavalse I have made it so the text inside the Button's dropdown menu won't wrap, which was especially undesirable with non-English scripts like Chinese characters.

fix: button widget squishing its text & infobox mask click away

---

src/components/molecules/Visualizer/Infobox/Frame/index.tsx

On mobiles, when you select a layer with an infobox with `Mask` option, it won't be selected

fix: cannot select layers that activate infobox mask

---

package.json
src/components/organisms/Common/AssetContainer/hooks.ts
src/gql/provider.tsx

Fixes an issue where navigating to the asset's settings page would make it so the asset results would have duplicate items. 
There seems to be an issue with apollo for some users ([this issue ](https://github.com/vuejs/apollo/issues/185)or similar) where the merge callback would be called twice.
This solution uses lo-dash to check the equality of the existing cache and incoming query in the merge function, so that if they match, they won't be merged together.

fix: duplicate asset results

---

src/components/organisms/Common/AssetContainer/hooks.ts
src/components/organisms/Common/AssetContainer/index.tsx
src/components/organisms/Settings/Workspace/hooks.ts

Fixes bug where changing workspace name would show error notification and not update UI until refresh.
Fixes bug where deleting consecutive assets would throw an error even though deletion was successful.

fix: workspace name cannot be changed, error displayed when deleting assets

---

src/components/molecules/Common/AssetModal/AssetContainer/hooks.ts
src/components/molecules/Common/AssetModal/AssetContainer/index.tsx
src/components/molecules/Common/AssetModal/AssetListItem/index.tsx
src/components/molecules/Common/AssetModal/index.tsx
src/components/molecules/EarthEditor/PropertyPane/PropertyField/URLField/index.tsx
src/components/organisms/Common/AssetContainer/index.tsx
src/components/organisms/Common/AssetModal/index.tsx

closes reearth/reearth#260
- Fix issue where file assets weren't selectable for things like 3d model primitives
- (Re)Add file icon for files
- Redo file upload restrictions
Note: asset modal now doesn't support limiting shown assets based on whether it is an image or file (at the code level).

fix: asset modal showing only image-based assets

---

src/gql/graphql-client-api.tsx
src/gql/queries.ts

When the user creates a new workspace from inside the setting page , the new workspace is created but the member section is empty and new member button disappears.
Change the graphql query and add the members to its result.

fix: members section and new member button disappear after creating workspace from setting

---

.github/renovate.json

closes https://github.com/reearth/reearth/issues/265
After updating the schedule for renovate bot, it didn't start on the new schedule. This should fix that

ci: fix renovate bot not running at scheduled time

---

package.json
src/components/molecules/PluginEditor/hooks.ts
src/components/molecules/PluginEditor/index.tsx
yarn.lock

When downloading your file in the plugin editor, the file would only copy some of the editor value. Not sure why this was happening, but the js-file-download dep works perfectly.
Also updated some names.

fix: downloaded file from plugin editor would only have partial code

---

src/components/organisms/Common/AssetContainer/hooks.ts
src/components/organisms/Dashboard/hooks.ts
src/components/organisms/EarthEditor/Header/hooks.ts
src/components/organisms/EarthEditor/TagPane/commonHooks.ts
src/components/organisms/Settings/Project/hooks.ts
src/components/organisms/Settings/ProjectList/hooks.ts
src/components/organisms/Settings/SettingPage/hooks.ts
src/components/organisms/Settings/Workspace/hooks.ts

The query names used in refetchQuery are not updated, which will lead to some components can't get auto updated after some mutaions.
Updated the query names in refetchQuery of hooks:
- GetAssets
- GetTeams
- GetSceneTags
- GetLayerTags
- GetProjects
Create & remove projects / teams(workspace) / scene tags / layer tags, upload / remove assets of image.

fix: Query names in refetchQueries not updated

---

i18next-parser.config.js
src/components/atoms/ConfirmationModal/index.tsx
src/components/molecules/Dashboard/Workspace.tsx
src/i18n/index.tsx

- I added `useT` hook to `@reearth/i18n` that enables writing translations with less typing.
- NOTE: Do not use other variable names than `t`, as translation will not be visible to the i18n-parser
- Disable i18n-parser option `useKeysAsDefaultValue` to clarify whether each text is translated or not. There is no effect on the on-screen display (if empty, the key is used as is).

chore: add useT hook to i18n

---

src/components/molecules/Visualizer/hooks.ts

close https://github.com/reearth/reearth/issues/297

fix: plugin API cameramove event is not emitted in published pages

---

src/config.ts

Just update config.ts so that devs can put an extension urls into their .env files locally
In .env
`REEARTH_WEB_EXTENSION_URLS=https://somewhere.com`
or multiple
`REEARTH_WEB_EXTENSION_URLS=https://somewhere.com,https://anothersomewhere.com,https://moresomewheres.com`

chore: update config so extensionUrls can be declared in .env file for local development

---

src/components/molecules/Visualizer/Block/Image/index.tsx

I fixed reearth/reearth#202.
I fixed to use `height: 100%;` when vertical position property is specified center in infobox image block.
|Before|After|
|-|-|
|![Screen Shot 2022-05-30 at 20 57 28](https://user-images.githubusercontent.com/34934510/170990175-125353f3-44ca-40cf-bbfb-7cff958ef42b.png)|![Screen Shot 2022-05-30 at 20 57 38](https://user-images.githubusercontent.com/34934510/170990198-2024fecd-ce0d-4428-bc28-f74af52266d9.png)|

fix: vertical position style in infobox image block

---

src/components/molecules/Visualizer/Engine/Cesium/Marker/index.tsx
src/components/molecules/Visualizer/Engine/Cesium/common.ts

In this PR I fixed the bug where the label is hidden behind the marker image
this fixes reearth/reearth#207 and reearth/reearth#184 reearth-web
I modified the `pixelOffset` hook inside `src/components/molecules/Visualizer/Engine/Cesium/Marker/index.tsx`
and updated the equations for x and y with taking imageSize(imageScale) in condsideration.
Manually using google chrome.

fix: labeling hidden by marker symbol

---

package.json
yarn.lock

close https://github.com/reearth/reearth/issues/300
The DnD feature comes from cesium-dnd. 
Upgrade cesium-dnd to 1.1.0 to support DnD in 2d/2.5d mode.
upgrade dependency cesium-dnd to 1.1.0
DnD markers in 3d/2d/2.5d mode

chore: upgrade dependency cesium-dnd to 1.1.0

---

src/components/molecules/Visualizer/Engine/Cesium/hooks.ts
src/components/molecules/Visualizer/Engine/Cesium/index.tsx

close https://github.com/reearth/reearth/issues/303
Internal state `Camera` got updated when engine cesium `Camera` `onChange` triggered;
Cesium camera use `percentageChanged` to control when trigger a onChange event;
When user capturing a new position, the internal camera does not get the latest cesium camera postion which lead to the shift.
Simply added `onMoveEnd` event handler to `Camera` so that camera state always got updated when move end.
Rename and split event handler for `onChange` and `onMoveEnd` although they do the same thing right now but maybe they will have defferent things to handle in the future.
Do capture position from the earth editor.
before capture:
after capture:

fix: slight shift when capture a new position

---

src/components/organisms/Settings/Project/Dataset/hooks.ts

On setting page/dataset, if refresh page, a warning appears
skip the undefined or empty scene id when fetching the dataset list

fix: dataset page showing errors on page refreshing 

---

src/components/molecules/Visualizer/Engine/Cesium/PhotoOverlay/hooks.ts
src/components/molecules/Visualizer/Engine/Cesium/hooks.ts

The earth flashes when zoom in/out or rotate fast.
I found the direct reason for this is from the hooks inside engine/cesium which is in order to fix camera fly bug with photooverlay. It will campare the `emittedCamera.current` with `camera` and if they're not equal then make a `flyto`.
These one should be equal in most situation but i found it not equal at most time now (maybe related to react v18 state update logic i'm not sure).
This is a quick fix, plz let me know if i misunderstood anything.
- remove the hook useEffect inside engine/cesium which is in order to fix camera fly bug with photooverlay so the flash will not happen
- fix photooverlay camera fly issue by always skip for unselected photooverlay item
- zoom in/out and rotate the earth fast to check the flash
- add markers and …

fix: Cesium flashes on camera change

---

src/components/organisms/EarthEditor/OutlinePane/hooks.tsx

Bug: when click on the 'create new folder' or move layer on the Outline pane -> layers, the layers list did not got update which will mislead the users.
Add refetch to `moveLayerMutation` and `addLayerGroupMutation`
- create new folder (add layer group)
- drag layer in/out of the folder
It seems to be an obvious bug and i'm not sure when it starts to happen.

fix: layers pane does not update after move layer or create folder 

---

src/components/molecules/Common/AssetModal/AssetContainer/hooks.ts
src/components/molecules/Common/AssetModal/AssetContainer/index.tsx
src/components/organisms/EarthEditor/PropertyPane/index.tsx

Fixed a bug where enabling the camera limiter would start an infinite render loop and prevent the selection of assets in the asset modal.

fix: asset modal flushes when camera limiter is enabled

---

src/components/molecules/Visualizer/Engine/Cesium/core/Indicator.tsx
src/components/molecules/Visualizer/Engine/Cesium/hooks.ts
src/components/molecules/Visualizer/Engine/Cesium/index.tsx

Fix the Dnd in selection indicator in cesium viewer.
Instead of disabling the selection indicator in the viewer constructor , I modified the element style itself , and by this way no need to reconstruct the viewer each time we change the indicator and also the Dnd should work fine.

fix: layer drag and drop does not work with indicators

---

src/components/molecules/Visualizer/hooks.ts

When click on blank space of map it should unselect layers but it doesn't work due to a bug.
The bug comes from updateing selectLayer functions of organisms `CanvasArea` and molecusles `Visualizer`. In the past the `CanvasArea` select funtion will check if the layer can be got by `layers.findById` and after update this condition should be moved into `Visualizer` selectLayer function. When reviewing, the code looks like can be refactored and i did it without thinking clearly. My mistake.  
Update the `selectLayer` function.
Select layer and click on blank space to unselect it.

fix: unselect layer not work properly

---

src/components/molecules/Visualizer/Plugin/context.tsx
src/components/molecules/Visualizer/hooks.ts

This PR fix three issues:
1. When create a new layer by drop the layer in Earth Editor, it doesn't got auto selected (No indicator shown on map).
- This issue also lead to when create a new infobox for this layer the Infobox popup doesn't show automaticlly.
- The bug comes from the state update: selectedLayer happens before layers data update so it got undefined.
- Why it works before is bc the setLayers with new created object will lead to anothor selectedLayer update which can get the latest layers data.
- In order to implement the update after layers data changed I replace the `useUpdate` with an internal implemtation (which refers to the source code of useUpdate but expose the state) and use the state as the dependence of `selectedLayer`.
2. When unselect a layer the plugin api …

fix: layer select state not update properly

---

src/components/molecules/Visualizer/Engine/Cesium/hooks.ts
src/components/molecules/Visualizer/Engine/Cesium/index.tsx

The `jump` button on camera pop-up pane doesn't work.
After some digging i found this bug comes from [another PR](https://github.com/reearth/reearth-web/pull/257) which was aiming at fix the view flash.
- I didn't realize the actual usage of some code and thought them only used to fix fly animation bug when using photooverlay as a patch - BUT actually this part of code has more basic task as accept global camera data change and update the Visualizer camera.
- I added them back to fix the `jump` bug. And again facing the view flash issue.
About the view flash issue I think it comes from the useEffect of global state `camera` (with Jotai) is somehow optimized after upgrade to React18. Here's some description in detail:
**Please correct me if i have anything misunderstood.**
- We have two …

fix: camera jump not working

---

src/components/molecules/EarthEditor/PropertyPane/PropertyField/CameraField/index.tsx

For some GIS engineers, showing a rounded value for camera values wasn't accurate enough so we now show full values.
Also, there was a margin still shown where the steps would have been in the number inputs, so those too have been removed for a cleaner and more accurate UI.

fix: show full camera values in camera property field popup

---

src/components/atoms/Plugin/IFrame/hooks.ts

When plugin didn't set width in API call (reearth.on.show....) the width would fall back to the iframe's default 300px width, making content have to scroll.

fix: plugin widget's width using iframe's default

---

src/components/molecules/Visualizer/Engine/Cesium/hooks.ts
src/components/molecules/Visualizer/Engine/Cesium/index.tsx
src/components/molecules/Visualizer/Engine/Cesium/useEngineRef.test.tsx
src/components/molecules/Visualizer/Engine/Cesium/useEngineRef.ts
src/components/molecules/Visualizer/Engine/ref.ts
src/components/molecules/Visualizer/Plugin/context.tsx
src/components/molecules/Visualizer/Plugin/hooks.ts
src/components/molecules/Visualizer/Plugin/types.ts

Touch to select does not work after pinch event on iPad.
This bug comes from unproper handle of pinch event props.
The pinch events are added with mouse events as a nice-to-have feature. Since the data type definiation is same with the mouse event props i didn't pay additional attention on the data but it turns out to be different.
After discuss with Red we decide to remove pinch events, the reasons are:
- Pinch events are not mouse events and should not be mix together.
- Pinch events carry different props which is different campared with mouse events.
- The main goal of mouse events API is to detect the target position or layer, which also can be done on touch device.
- The pinch event actually do zoom or rotate which are different usecases.
Also if we got some requirements in detail …

fix: select not working after pinch event on ipad

---

src/components/atoms/Plugin/IFrame/hooks.ts

We used a `forEach` to trigger the execute of script inside a plugin iframe html which will lose the loading order like it is handled in a normal browser. 
- Replace the code with a Promise for each script so that the scripts can load in order.
- The scripts with attribute `async` `defer` or has `type="module"` (which will be handled as defer by browser) will be loaded last.
- Updated the `onLoad` part. This should be emitted after sync scripts loaded or there's no script.
- Test with plateauview plugin which use cdn React & ReactDOM.
Before:
After:
Btw the assets issue is not related with this.

fix: iframe scripts are not loaded with order

---

src/components/atoms/Button/index.tsx
src/components/atoms/Icon/index.tsx

fix: icon button transition happening when undesired

---

src/components/molecules/Visualizer/Engine/Cesium/useEngineRef.test.tsx
src/components/molecules/Visualizer/Engine/Cesium/useEngineRef.ts
src/components/molecules/Visualizer/Engine/ref.ts
src/components/molecules/Visualizer/Plugin/api.ts
src/components/molecules/Visualizer/Plugin/context.tsx
src/components/molecules/Visualizer/Plugin/types.ts
src/components/molecules/Visualizer/hooks.ts
src/components/molecules/Visualizer/storybook.tsx

This feature enables plugin get the image of the map.
Without this API the plugin can manually get the canvas and use `canvas.toDataURL` but the result will be a full black image due to the canvas webgl settings.
The solutions are:
A: Config contextOptions with `{{ webgl: { preserveDrawingBuffer: true } }}` but this will technically harm the performance so i did not apply this.
B: Call `canvas.toDataURL` immediately after a `viewer.render`. This is what i implemented for the API.
**NOTICE**: the output image comes from the canvas so anything implemented out of canvas (eg. infobox) can not be included. If you want to take a screenshot of all HTML elements you may try implement with some third-party libraries in plugin code.
Extend the plugin API with 
```
reearth.scene.captureScreen: …
```

feat: extend plugin api with captureScreen

---

src/components/molecules/Visualizer/Engine/Cesium/Tileset/index.tsx

OSM Buildings is a 3D buildings layer covering the entire world. It's available as a 3D Tileset on Cesium.
we modified reearth  in way that allows the user to add OSM building 3d Tileset as a layer.
backend pr : https://github.com/reearth/reearth/pull/340

feat: add 3D OSM building tiles

---

src/components/molecules/Visualizer/Plugin/api.ts

The exposed API `reearth.layers.add` doesn't return the new layer's id as expected.
Add return value to the exposed add function.
Tested with plugin:
```
const id = reearth.layers.add({extension:'marker'});
console.log(id);
```

fix: exposed plugin api add layer does not return layer id

---

src/components/molecules/Visualizer/Engine/Cesium/index.tsx
src/components/molecules/Visualizer/Engine/ref.ts

feat: add option to allow camera to enter the earth's surface

---

src/components/molecules/Visualizer/Engine/Cesium/common.ts
src/components/molecules/Visualizer/Engine/Cesium/hooks.ts

Mouse events want to get the correct location when terrain is on.
Update the common `getLocationFromScreenXY` function, added a prop `withTerrain` default as `false`.
If `withTerrain` is `true` it will use `globe.pick` instead of `camera.pickEllipsoid` so that terrain can take effect. And if doesn't get the location it will still try `camera.pickEllipsoid` as a polyfill.
Tested with plugin using mouse event.

feat: support acquiring locations with terrain

---

src/components/molecules/Visualizer/Engine/Cesium/common.ts
src/components/molecules/Visualizer/Engine/Cesium/hooks.ts
src/components/molecules/Visualizer/Engine/Cesium/useEngineRef.test.tsx
src/components/molecules/Visualizer/Engine/Cesium/useEngineRef.ts
src/components/molecules/Visualizer/Engine/ref.ts
src/components/molecules/Visualizer/Plugin/api.ts
src/components/molecules/Visualizer/Plugin/context.tsx
src/components/molecules/Visualizer/Plugin/types.ts
src/components/molecules/Visualizer/hooks.ts
src/components/molecules/Visualizer/storybook.tsx

Plugin need to get the location of certain point on screen.
Expose `getLocationFromScreen` to plugin API.
```ts
reearth.scene.getLocationFromScreen(x: number, y:number, withTerrain?:boolean) 
=> LatLngHeight | undefined
type LatLngHeight = {
lat: number;
lng: number;
height: number;
};
```
Tested with devtool console.
Tested with plugin editor using:
```js
reearth.ui.show(`
<style>
html,
body {
margin: 0;
width: 350px;
font-size: 14px;
}
button {
margin: 0;
}
#wrapper {
height: 100%;
box-sizing: border-box;
border-radius: 12px;
padding: 12px;
background: white;
}
#wrapper {
box-sizing: border-box;
border-radius: 12px;
background: white;
height: 100%;
}
h3{
margin: 0 0 5px;
}
h4{
margin: 5px 0;
}
#currentUnitLine{
height: 2px;
background: #000;
width: 0;
}
</style>
<div id="wrapper"> …
```

feat: extend plugin API supports get location from screen position

---

src/components/molecules/Visualizer/Plugin/hooks.ts
src/components/molecules/Visualizer/Plugin/types.ts

close https://github.com/reearth/reearth/issues/366
Extend plugin API events with `modalclose` and `popupclose`.
Implement the API:
```js
reearth.on('modalclose', () => {});
reearth.on('popupclose', () => {});
```
Tested with plugin:
```js
reearth.ui.show(`
<style>
html,
body {
margin: 0;
width: 350px;
font-size: 14px;
}
button {
margin: 0;
}
#wrapper {
height: 100%;
box-sizing: border-box;
border-radius: 12px;
padding: 12px;
background: white;
}
.extendedh {
width: 400px;
}
.extendedv {
height: 400px;
}
#wrapper {
box-sizing: border-box;
border-radius: 12px;
background: white;
height: 100%;
}
.extendedh body,
.extendedh #wrapper {
width: 100%;
}
.extendedv body,
.extendedv #wrapper {
height: 100%;
}
h3{
margin: 0 0 5px;
}
h4{
margin: 5px 0;
}
</style>
<div id="wrapper">
<h3>Modal/Popup …
```

feat: extend plugin API event with modalclose popupclose

---

src/components/molecules/Visualizer/Engine/Cesium/common.ts

The `flyToGround` API used a wrong destination camera. 
Correct the destination camera using the param camera.
Test with plugin pedestrain.

fix: correct flyToGround destination camera

---

src/components/atoms/Plugin/PluginIFrame/hooks.ts
src/components/atoms/Plugin/PluginIFrame/index.tsx
src/components/atoms/Plugin/PluginIFrame/useIFrame.ts
src/components/molecules/Visualizer/Plugin/hooks.ts

The `usePostMessage` posts queue message when param `avaliable`(!ready || !iFrameLoaded) changes.
When modal/popup disabled, the state of `iFrameLoaded` should be set to `false` so that when it enabled the postMessage can be properly triggered.
- Pass `enabled` to useIFrame in order to set the `iFrameLoaded` state.
- Do some refactor on `modalVisible` & `popupVisible`, using state instead of ref. 
Tested with plugin:
```js
const ui = `
<style>
html,
body {
margin: 0;
width: 350px;
font-size: 14px;
}
button {
margin: 0;
}
#wrapper {
height: 100%;
box-sizing: border-box;
border-radius: 12px;
padding: 12px;
background: white;
}
.extendedh {
width: 400px;
}
.extendedv {
height: 400px;
}
#wrapper {
box-sizing: border-box;
border-radius: 12px;
background: white;
height: 100%;
}
.extendedh body, …
```

fix: post message queue doesn't work for modal/popup

---

src/components/molecules/Visualizer/Engine/Cesium/useEngineRef.ts
src/components/molecules/Visualizer/Engine/ref.ts

I added `animation` option to lookAt function. This option makes lookAt function work without animation.
But the name that called `animation` is miss context, so I fixed this name to `withoutAnimation`.
https://github.com/reearth/reearth-web/pull/338/files#diff-0b5055db5c2f9046c0a43a5d935daac31c9eff33ee864fe1f90cc7f890932e09R84

fix: rename animation option to withoutAnimation in lookAt

---

src/components/organisms/Notification/hooks.ts
src/config/index.ts
src/i18n/translations/ja.yml

fix: policy messages not aligning with policy

---

src/components/molecules/Visualizer/Engine/Cesium/index.tsx
src/core/engines/Cesium/index.tsx

I removed `imageryProvider={false}` props for Viewer component.
This props removes the loaded globe image. The props is used in [here](https://github.com/reearth/resium/blob/41070fb25b32e9a18e09814b615b8728a51214b8/src/Viewer/Viewer.ts#L143).
Therefore this cause unnecessary loading globe image when the Viewer component is re-rendered.

perf: improve unnecessary loading the globe image

---

package.json
src/core/engines/Cesium/hooks.ts
src/core/engines/Cesium/index.tsx
yarn.lock

I fixed the bug that does not render the layer even when updating the property for layer.
This is because, the old system is updated every clock event is occurred but the new layer system disable this behavior for performance, so we need to call `scene.requestRender` manually.
Also I fixed resium in https://github.com/reearth/resium/pull/568.
~~TODO: I will update the resium when @rot1024 -san publish it.~~
1. Open storybook
2. Change the color of marker on storybook(That works)
3. Change the coordinates of marker on storybook(That didn't work but currently that should work)

fix: rendering bug in new layer system

---

src/core/mantle/data/geojson.ts
src/core/mantle/types/index.ts

I've supported the multi feature for geojson.
The multi feature includes `MultiPoint`, `MultiLineString` and `MultiPolygon`.
You can use the following sample geojson.
1. Download the sample
2. Set it to `.storybook/public`
3. Set the path in `core/engine/Cesium/index.stories.tsx`
[sample.zip](https://github.com/reearth/reearth-web/files/10255142/sample.zip)

feat: support multi feature for geojson

---

src/core/Map/types/event.ts
src/core/Map/types/index.ts
src/core/engines/Cesium/Feature/Box/Edge.tsx
src/core/engines/Cesium/Feature/Box/ScalePoints.tsx
src/core/engines/Cesium/Feature/Box/Side.tsx
src/core/engines/Cesium/Feature/Box/constants.ts
src/core/engines/Cesium/Feature/Box/hooks/box.ts
src/core/engines/Cesium/Feature/Box/hooks/edge.ts
src/core/engines/Cesium/Feature/Box/hooks/scalePoint.ts
src/core/engines/Cesium/Feature/Box/hooks/side.ts
src/core/engines/Cesium/Feature/Box/index.tsx
src/core/engines/Cesium/Feature/Box/utils.ts
src/core/engines/Cesium/Feature/Tileset/hooks.ts
src/core/engines/Cesium/Feature/Tileset/index.tsx
src/core/engines/Cesium/Feature/context.ts
src/core/engines/Cesium/Feature/index.tsx
src/core/engines/Cesium/hooks.ts
src/core/engines/Cesium/index.tsx
src/core/mantle/types/appearance.ts
src/core/mantle/types/value.ts
src/util/value.ts

I have ported the Box layer into the reearth/core/features.
Also I have ported the clipping feature logic into Tileset component in the reearth/core/features.

feat: port the Box layer into the reearth/core

---

src/components/molecules/Visualizer/Plugin/api.ts

There's a type missing on function `exposed` modal.show / popup.show options. 
It doesn't effect the functionality but better to correct it anyway.
Add missing types.
Test with plugin:
[modalpopup.zip](https://github.com/reearth/reearth-web/files/10443695/modalpopup.zip)

fix: missing type of API modal & popup options. 

---

src/core/engines/Cesium/Feature/Resource/index.stories.tsx
src/core/engines/Cesium/Feature/Resource/index.tsx
src/core/engines/Cesium/Feature/Resource/utils.test.ts
src/core/engines/Cesium/Feature/Resource/utils.ts
src/core/engines/Cesium/Feature/utils.tsx

I implemented overriding  czml appearance support on reearth/core.

feat: support overriding czml appearance on reearth/core

---

src/auth/provider.tsx

Add `offline_access` scpe to support refresh tokens with built-in auth server

chore: add offline_access auth scope to support refresh tokens with built-in auth server (#425

---

src/core/engines/Cesium/Feature/Resource/index.tsx

Resource feature component load geojson even if geojson is already rendered by other appearance like marker.
So I fixed this bugs.

fix: GeoJSON with resource appearance on reearth/core

---

src/core/Crust/Plugins/api.ts
src/core/Crust/Plugins/hooks.ts
src/core/Crust/Plugins/plugin_types.ts
src/core/Crust/Plugins/types.ts
src/core/Crust/index.tsx
src/core/Map/Layers/hooks.ts
src/core/engines/Cesium/Feature/Tileset/hooks.ts
src/core/engines/Cesium/hooks.ts
src/core/engines/Cesium/useEngineRef.ts
src/core/engines/Cesium/utils.ts

- Added `layers.selectedFeature` API
- Extend `layers.select(layerId, option)` to take featureId like `layers.select(layerId or featureId, option)`
- Support selecting 3DTileFeature.
- Support selecting imagery layer

feat: support select feature on reearth/core

---

src/core/Crust/Plugins/api.ts
src/core/Crust/Plugins/plugin_types.ts
src/core/Map/Layers/hooks.ts
src/core/Map/Layers/index.tsx
src/core/Map/index.tsx
src/core/Visualizer/hooks.ts
src/core/engines/Cesium/hooks.ts

- Renamed overriddenInfobox to defaultInfobox
- Changed overriddenInfobox not to override infobox, and it should behave as default value

fix: use default infobox on reearth/core

---

src/core/engines/Cesium/Feature/Tileset/hooks.ts

I referred appearance from computed layer in Tileset component, so I fixed to refer appearance from simple layer.

fix: 3dtiles overriding appearance behavior on reearth/core

---

src/core/engines/Cesium/Feature/Box/Edge.tsx
src/core/engines/Cesium/Feature/Box/ScalePoints.tsx
src/core/engines/Cesium/Feature/Box/Side.tsx
src/core/engines/Cesium/Feature/Box/hooks/box.ts
src/core/engines/Cesium/Feature/Box/index.tsx
src/core/engines/Cesium/Feature/Ellipsoid/index.tsx
src/core/engines/Cesium/Feature/Marker/index.tsx
src/core/engines/Cesium/Feature/Model/index.tsx
src/core/engines/Cesium/Feature/PhotoOverlay/index.tsx
src/core/engines/Cesium/Feature/Polygon/index.tsx
src/core/engines/Cesium/Feature/Polyline/index.tsx
src/core/engines/Cesium/Feature/utils.tsx
src/core/mantle/types/appearance.ts
src/core/mantle/types/value.ts

```
data: {
type: "csv",
// url: "xxx.csv",
value: `id,lat,lng,height,name\n1,0,0,0,hoge`,
csv: {
idColumn: "id",
latColumn: "lat",
lngColumn: "lng",
heightColumn: "height",
noHeader: false,
}
},
marker: {
imageColor: {
expression: "${name} === 'hoge' ? color('blue') : color('red')",
},
distanceDisplayCondition: {
near: 100000,
}
}
});
```

feat: support distanceDisplayCondition on reearth/core

---

src/core/mantle/data/gtfs.ts

This PR adds vehicle property to the GeoJSON Point obtained for the GTFS feed.

fix: add properties in vehicle point for gtfs

---

src/core/Map/Layers/hooks.test.ts
src/core/Map/Layers/hooks.ts
src/core/Map/Layers/utils.test.ts
src/core/Map/Layers/utils.ts

```js
const id = reearth.layers.add({
data: { 
type: "geojson",
value: { // GeoJSON
"type": "Feature",
"geometry": {
"coordinates": [
-15.209829106984472,
20.323569554406248,
10000
],
"type": "Point"
}
}
},
});
reearth.layers.override(id, { marker: {} });
reearth.layers.override(id, { marker: undefined }); // appearance will be removed
```

fix: revert appearance to initial value when appearance is undefined on reearth/core

---

src/core/engines/Cesium/Feature/index.tsx

fix: recreate no feature component when data url is changed on reearth/core

---

src/core/Crust/Widgets/Widget/Timeline/hooks.ts
src/core/Crust/context.ts
src/core/engines/Cesium/core/Clock.tsx

Current time is reset on timeline every time camera is moved, so I fixed to prevent unnecessary render.

fix: prevent unnecessary render on timeline on reearth/core

---

src/core/Crust/Plugins/api.ts
src/core/Map/Layers/index.tsx
src/core/Map/Layers/utils.ts
src/core/Map/index.tsx

We can not refer `reearth.layers.layers`'s properties. Because `layers` are computed asynchronously, so we are wrapping layers with `Object.defineProperties` to refer property lazily.
But quickjs can not refer these property. For example, when we run `Object.keys(lazyLayers)`  then the result returns only `id` property.
So I fixed to copy these value when layers are referred on plugin.

fix: copy lazy layer on plugin on reearth/core

---

src/core/mantle/evaluator/simple/expression/variableReplacer.test.ts
src/core/mantle/evaluator/simple/expression/variableReplacer.ts

This PR fixes an issue when properties key contains `hyphen` in them.

fix: parse hyphen as reserved word in property key on reearth/core

---

src/core/mantle/data/csv.test.ts
src/core/mantle/data/csv.ts
src/core/mantle/types/index.ts

This PR fixes a issue observed while parsing csv files. It makes sure the numerical string get parsed as number instead of string but if the user deemed it to string they can do so by using `disableTypeConversion: true` in `csv` of `data` property.

fix: parse csv numeric strings as numbers in reearth/core

---

src/core/Crust/Widgets/Widget/Timeline/hooks.ts
src/core/mantle/atoms/data.ts
src/core/mantle/data/csv.ts
src/core/mantle/data/geojson.ts
src/core/mantle/data/georss.ts
src/core/mantle/data/gml.ts
src/core/mantle/data/gpx.ts
src/core/mantle/data/gtfs.ts
src/core/mantle/data/index.ts
src/core/mantle/data/shapefile.ts
src/core/mantle/data/utils.ts

When we override layer on adding layer, overriding process is skipped if data atom is fetching.
So I fixed to abort only fetching process, not skip entire overriding process.

fix: abort fetching on data atom on reearth/core

---

src/core/Crust/Widgets/Widget/Timeline/hooks.ts
src/core/Crust/context.ts
src/core/Crust/index.tsx
src/core/Map/types/index.ts
src/core/Visualizer/hooks.ts
src/core/Visualizer/index.tsx
src/core/engines/Cesium/core/Clock.tsx
src/core/engines/Cesium/index.tsx

I fixed overriding timeline behavior on [this PR](https://github.com/reearth/reearth-web/pull/528).
But this PR cannot affect settings to Cesium side correctly. So I fixed to affect overriding timeline setting to Cesium.

fix: overriding timeline behavior on reearth/core

---

src/core/Crust/Infobox/types.ts
src/core/engines/Cesium/Feature/Resource/utils.ts
src/core/engines/Cesium/hooks.ts
src/core/engines/Cesium/utils.ts
src/core/mantle/compat/types.ts

sample code
```js
data: {
type: "czml",
url: "{CZML URL}",
},
resource: {},
infobox: {
property: {
default: {
defaultContent: "attributes" // or "description"
}
}
}
});
```

feat: add defaultContent property for infobox in plugin API on reearth/core

---

src/core/engines/Cesium/Feature/Resource/index.tsx
src/core/engines/Cesium/hooks.ts

It should work.
```
const id = reearth.layers.add({
data: {
type: "czml",
url: "https://assets.cms.plateau.reearth.io/assets/b0/9701c5-79cc-437a-b807-1593ffa2a034/28225_asago-shi_landmark.czml",
},
resource: {},
infobox: {
property: {
default: {
defaultContent: "attributes" // or "description"
}
}
}
});
reearth.layers.override(id, { infobox: {
property: {
default: {
defaultContent: "attributes"
}
}
}});
```

fix: use overriddenLayers to get infobox on reearth/core

---

src/core/mantle/evaluator/simple/expression/expression.ts

I improved performance of 3dtiles.
The cause of problem is, TypeScript transpiles class private field(eg `#name`) by using global `WeakMap` like the following.
In the following code, WeakMap is defined on global. So this code store `feature` with each instance to same WeakMap. 
So this WeakMap will consume very large memory.
So I fixed to use `private` modifier. This modifier is removed in build time.
```js
var ts = (AA,eA,tA)=>{
if (eA.has(AA))
throw TypeError("Cannot add the same private member more than once");
eA instanceof WeakSet ? eA.add(AA) : eA.set(AA, tA)
}
var fQ, kC, KC;
class Expression {
constructor(eA, tA, rA) {
ts(this, fQ, void 0);
ts(this, kC, void 0);
ts(this, KC, void 0);
// Doing something
}
// Doing something
}
fQ = new WeakMap,
kC = new WeakMap,
KC = new WeakMap; …
```

perf: use private modifier on evaluator on reearth/core

---

src/core/Map/Layer/hooks.ts
src/core/Map/Layer/index.tsx
src/core/Map/Layers/index.test.tsx
src/core/engines/Cesium/Feature/Raster/hooks.ts
src/core/engines/Cesium/Feature/Raster/index.tsx
src/core/engines/Cesium/Feature/Resource/index.tsx
src/core/engines/Cesium/Feature/Tileset/hooks.ts
src/core/engines/Cesium/Feature/Tileset/index.tsx
src/core/engines/Cesium/Feature/index.tsx
src/core/engines/Cesium/Feature/utils.tsx
src/core/mantle/atoms/compute.test.ts
src/core/mantle/atoms/compute.ts
src/util/idle.ts

I fixed deleting feature process.
- Fixed to delete feature cached on atom when delegated feature is unmounted.
- Fixed to recreate noFeature component when `isVisible` is changed.

fix: deleting feature process on reearth/core

---

src/components/molecules/Visualizer/Block/HTML/index.tsx
src/components/molecules/Visualizer/Block/index.tsx
src/components/molecules/Visualizer/Infobox/index.tsx
src/core/Crust/Infobox/Block/HTML/index.tsx
src/core/Crust/Infobox/Block/index.tsx
src/core/Crust/Infobox/index.tsx

Safari doesn't support load event with srcDoc, so I fixed to use `document.write()`...

fix: htmlblock on safari

---

src/core/engines/Cesium/Feature/Polygon/index.tsx
src/core/mantle/types/appearance.ts

This PR adds support for height in polygon appearance and polygon graphic parameters in reearth/core.

fix: add height to polygon in reearth/core

---

src/core/mantle/evaluator/simple/conditionalExpression/index.ts
src/core/mantle/evaluator/simple/expression/constants.ts
src/core/mantle/evaluator/simple/expression/expression.ts
src/core/mantle/evaluator/simple/expression/functions/colors.ts
src/core/mantle/evaluator/simple/expression/node.ts
src/core/mantle/evaluator/simple/expression/runtime.ts
src/core/mantle/evaluator/simple/expression/variableReplacer.ts
src/core/mantle/evaluator/simple/index.ts

I added some performance optimisations for the style evaluator which includes using 
1. using `switch-case` for long chain of `if-else`.
2. use less heavy string operations in replaceVariable.
2. Memoization of the regularly used regex.
3. Remove a highly imported function(`defined`) which is relatively slower than `typeOf`.
4. Using private fields instead of using prefix `#`

perf: reduce style evaluator memory signature in reearth/core

---

src/core/Crust/Infobox/Frame/index.tsx
src/core/Crust/Infobox/index.tsx
src/core/Crust/Infobox/types.ts
src/core/Crust/index.tsx
src/core/Visualizer/hooks.ts
src/core/Visualizer/index.tsx
src/core/mantle/compat/types.ts

Infobox shows a small UI panel when click close button. 
This PR adds a `unselectOnClose` property to infobox so that infobox can trigger a unselect on close and the UI will be fully invisible automatically.
- Add property `unselectOnClose`
- Unselect layer when infobox close and unselectOnClose is true.
- Did not add this property on reearth backend. It's useful for infobox added by plugin API but can't be set with reearth editor.
Test with:
```javascript
data: { 
type: "geojson",
value: {
"type": "Feature",
"geometry": {
"coordinates": [-15, 20, 10000],
"type": "Point"
}
}
},
marker: {},
infobox: {
blocks: [],
property: {
default: {
title: 'Unselect On Close',
unselectOnClose: true
}
}
}
});
data: { 
type: …
```

feat: option to unselect layer when click infobox close

---

src/core/engines/Cesium/Feature/Polygon/index.tsx
src/core/mantle/types/appearance.ts

Reverts reearth/reearth-web#557
As discussed this fix doesn't work well with clampToGround the polygon.

fix: revert add height to polygon in reearth/core

---

src/core/Crust/Widgets/Widget/Timeline/hooks.ts

fix: override currentTime on timeline widget when time is updated by CZML on reearth/core

---

src/core/mantle/evaluator/simple/expression/node.ts

This PR changes the behaviour of evaluation of logical operators in reearth/core. If statement aren't valid, logical operators with return `false` as a default output. This behaviour in turn helps in fallback to default condition for conditional style which have invalid reference.

fix: change logical operator evaluation behaviour in reearth/core

---

src/core/Crust/Plugins/api.ts

Add `startEventLoop` for trigger event on vm.

fix: sample terrain height API cannot properly return promise

---

src/core/engines/Cesium/Feature/Resource/index.tsx
src/core/mantle/types/appearance.ts

This PR adds more styling option on Resource Apperance in reearth/core and related refactors.

feat: add more styling properties to resource appearance in reearth/core

---

src/core/engines/Cesium/Feature/Model/index.tsx

This PR removes the `default` height reference(clamp) for the Model Graphics as it is making it impossible to render some `glb` or `glTF` files.

fix: remove default height reference for modelGraphics in reearth/core

---

src/core/engines/Cesium/Feature/Tileset/hooks.ts

3dtiles with no features are rendered as model, therefore the style of `coloe` `show` should also been included.
- Add `show` `color` to `MODEL_STYLE_PROPERTIES`
- Convert `show` `color` to match the type of style object for new Cesium3DTileStyle().
```js
type: 'simple',
data: {
type: '3dtiles',
url: "https://assets.cms.plateau.reearth.io/assets/0a/a2581a-e2cd-462a-a78b-a86841c477e9/uc22-024_sensynrobotics_kawasaki_build_2/tileset.json"
},
"3dtiles": {
show: {
"expression": {
"conditions": [
[
"true",
"true"
]
]
}
},
color: {
"expression": {
"conditions": [
[
"true",
"rgba(255,0,0,0.5)"
]
]
}
}
}
})
```

feat: support styling color & show for 3dtiles model

---

src/core/mantle/evaluator/simple/expression/node.ts

This is a fix for a issue observed while using the styling with `Number()` function whose input is not `string`

fix: resolve endsWith is not a function error with style in reearth/core

---

src/core/engines/Cesium/Feature/Raster/index.tsx
src/core/engines/Cesium/Feature/Raster/tms.ts
src/core/engines/Cesium/Feature/index.tsx
src/core/mantle/types/index.ts

[Documentation of TileMapService is here](https://cesium.com/learn/cesiumjs/ref-doc/TileMapServiceImageryProvider.html)
NOTE: Specified `url` should not be template url like `https://example.com/{z}/{x}/{y}`. We need to specify only url for raster like `https://example.com/path/to/raster`, and `TileMapServiceImageryProvider` can request png to `https://example.com/path/to/raster/{z}/{x}/{y}.png` by referring `https://example.com/path/to/raster/tilemapresource.xml` automatically.
```js
const id = reearth.layers.add({
data: {
type: "tms",
url: "https://example.com/path/to/png",
},
raster: {
alpha: 0.8
}
});
```

feat: support TileMapService(TMS) on reearth/core

---

package.json
src/core/engines/Cesium/Feature/Resource/index.tsx
src/core/engines/Cesium/Feature/index.tsx
yarn.lock

The PR adds support for large `geojson` type of data.
With the current approach of considering `geojson` only works to a limit of around 14k featureCollection in a layer, any data containing more features gives a WebGL error which basically means that `Cesium` cannot handle any more individual graphics component i.e `PolygonGraphics`, `PolylineGraphics` etc. 
As of now I've added a threshold limit of `6000` for featureCollection size, for geojson to be considered as an `active` data format in NLS and the size is large we consider it as a `delegate` data format.
Pros:
- We can now accommodate very large geojson with this approach now.
- We also save alot of overhead.
Cons:
- We lose the ability to custom styling on this data.
- With this approach, we can only handle featureCollection of …

perf: consider geojson as both delegate and active data type in reearth/core

---

src/util/use-core.ts

`fields[0]` is not reliable since there's multiple experimental items now.
This may lead to recently created project can't apply useCore in earth editor.

fix: use core hook may get value incorrectly
