src/components/molecules/EarthEditor/InfoBox/InfoBoxFrame/index.tsx

Fixes issue on large smartphones(iphone 12 pro max)

fix: large infobox on mobile

---

src/components/molecules/Visualizer/Engine/Cesium/Marker/index.stories.tsx
src/components/molecules/Visualizer/Engine/Cesium/Marker/index.tsx
src/components/molecules/Visualizer/Engine/Cesium/PhotoOverlay/index.tsx
src/components/molecules/Visualizer/Engine/Cesium/common.ts
src/components/molecules/Visualizer/Engine/Cesium/index.tsx
src/components/molecules/Visualizer/Engine/Cesium/useEntitySelection.ts
src/components/molecules/Visualizer/Engine/ref.ts
src/components/molecules/Visualizer/Infobox/Frame/index.stories.tsx
src/components/molecules/Visualizer/Widget/Menu/index.tsx
src/components/molecules/Visualizer/Widget/SplashScreen/index.tsx
src/components/molecules/Visualizer/Widget/Storytelling/index.tsx

Fixes:
- Layers without title are not recognized by storytelling widget
- Menu widget is not displayed
- Camera won't fly with splash screen widget
- Timing of the start of splash screen is too early
- Disable Cesium's default double click event
- Marker label position is opposite to the actual display

fix: visualizer bugs

---

src/components/organisms/Settings/Workspace/Asset/queries.ts
src/gql/fragmentMatcher.json
src/gql/graphql-client-api.tsx
src/gql/graphql.schema.json

Increaded the Asset query's max from 100 items to 300.

fix: asset limit too low

---

src/components/molecules/Common/plugin/builtin/primitives/marker.tsx

Fix bug that marker label position is oposite to actual display.

fix: marker label position is oposite to actual display

---

src/components/molecules/EarthEditor/InfoBox/InfoBox/hooks.ts
src/components/molecules/EarthEditor/InfoBox/InfoBoxFrame/index.tsx

Support multi-line infobox titles. Long word will also break automatically.

feat: support multi-line infobox titles

---

src/components/molecules/EarthEditor/PropertyPane/PropertyItem/index.tsx

fix: properties title

---

README.md

feat: refine readme

---

.storybook/preview.tsx

Wrapped `Theme` with client mock (which is using apollo to choose theme)

fix: storybook

---

.storybook/preview.tsx

fix: storybook error

---

src/components/molecules/Common/MenuList/index.tsx
src/components/molecules/Dashboard/QuickStart.tsx
src/theme/theme.ts
src/theme/z-index.ts

Fix bug where header changes height depeneding on what is selected in the panels.
Add transition to quickstart button.
Clean up Menu component.

fix: header bug

---

codegen.yml
src/components/organisms/EarthEditor/CanvasArea/hooks.ts
src/components/organisms/EarthEditor/PropertyPane/convert.ts
src/components/organisms/EarthEditor/PropertyPane/hooks.ts
src/components/organisms/EarthEditor/PropertyPane/queries.ts
src/gql/fragmentMatcher.json
src/gql/fragments/property.ts
src/gql/graphql-client-api.tsx
src/gql/graphql.schema.json

Update GraphQL schema to follow https://github.com/reearth/reearth-backend/pull/70

chore: follow backend GraphQL schema update

---

src/components/atoms/Plugin/hooks.ts
src/components/atoms/Plugin/index.tsx
src/components/molecules/Visualizer/Layers/store.ts
src/components/molecules/Visualizer/Plugin/api.ts
src/components/molecules/Visualizer/Plugin/hooks.ts
src/components/molecules/Visualizer/Plugin/types.ts

Fix plugin layer APIs would not work as expected. Layer objects would be undefined in the plugin runtime.

fix(plugin): layers would not be marshalled correctly

---

src/components/molecules/Visualizer/Engine/Cesium/PhotoOverlay/hooks.ts

fix: photooverlay transition does not work in Android

---

src/components/molecules/Visualizer/Engine/Cesium/Cluster.tsx
src/components/molecules/Visualizer/Engine/Cesium/PhotoOverlay/hooks.ts
src/components/molecules/Visualizer/Engine/Cesium/index.tsx
src/components/molecules/Visualizer/Engine/Cesium/useEngineRef.ts
src/components/molecules/Visualizer/Engine/index.tsx
src/components/molecules/Visualizer/Engine/ref.ts
src/components/molecules/Visualizer/Layers/index.tsx
src/components/molecules/Visualizer/index.tsx

Refactor cluster feature code
- Fix dependency flow
- Remove code duplication
- Make code clearer
- Change functionality
- Re-tested cluster feature.
Thanks @rot1024

refactor: layer clustering feature

---

src/components/molecules/Visualizer/Engine/Cesium/Resource/index.tsx

feat: add "clamp to filed" option to file primitive

---

.gitignore
src/components/molecules/Visualizer/Block/Text/index.tsx
src/components/molecules/Visualizer/Infobox/Frame/index.tsx
src/components/molecules/Visualizer/Infobox/index.tsx
src/components/molecules/Visualizer/Plugin/types.ts

feat: Infobox padding

---

src/components/molecules/Visualizer/Infobox/Frame/index.tsx

fix: padding for closed infobox

---

.github/renovate.json

Change from earlyMondays to the 4th of every month so its not as noisy

ci: change renovate schedule

---

codegen.yml
src/components/molecules/Settings/Workspace/AddMemberModal/index.tsx
src/components/molecules/Settings/Workspace/MembersSection/index.tsx
src/components/organisms/EarthEditor/CanvasArea/queries.ts
src/components/organisms/EarthEditor/DatasetInfoPane/queries.ts
src/components/organisms/EarthEditor/OutlinePane/queries.ts
src/components/organisms/EarthEditor/PrimitiveHeader/queries.ts
src/components/organisms/EarthEditor/PropertyPane/queries.ts
src/components/organisms/Settings/Account/queries.ts
src/components/organisms/Settings/Project/Plugin/queries.ts
src/components/organisms/Settings/Workspace/hooks.ts
src/components/organisms/Settings/Workspace/queries.ts
src/gql/graphql-client-api.tsx
src/gql/graphql.schema.json

Follow GraphQL schema updates at https://github.com/reearth/reearth-backend/pull/135
I tested the app manually and I confirmed it works

chore: follow GraphQL schema updates

---

.github/changelog.json
.github/workflows/build.yml
.github/workflows/deploy_test.yml
.github/workflows/e2e.yml
.github/workflows/pr_title.yml
.github/workflows/release.yml

Update GitHub actions to build and release rc

ci: create rc release for release branch

---

src/components/molecules/Visualizer/Plugin/api.ts

fix: some plugin APIs were missing

---

src/components/molecules/Common/AssetModal/index.tsx

fix: not being able to override an image from the asset modal

---

src/components/atoms/Timeline/ScaleList.test.tsx
src/components/atoms/Timeline/index.test.tsx

- fix test of timeline component for vitest
run `yarn test` and check if test is passing

test: fix test for vitest in timeline component

---

src/components/molecules/Settings/SettingPage/index.tsx

fix: device settings menu icon getting squished

---

src/components/atoms/Timeline/hooks.ts
src/components/atoms/Timeline/index.tsx
src/components/molecules/Visualizer/Widget/Timeline/hooks.ts

I fixed some issue in timeline widget.
- I fixed non-expanded timeline to be unexpectedly height
- I fixed the issue that speed slider didn't work
**unexpectedly height issue**
**speed issue**
https://user-images.githubusercontent.com/34934510/187675612-6a1f1220-05d9-4796-b0d5-79f4bfea0ac3.mov

fix: play button does not work and some unexpected style on timeline widget

---

src/components/atoms/Button/index.tsx
src/components/atoms/Icon/index.tsx

fix: icon size being too small

---

src/components/molecules/Settings/Project/Plugin/PluginSection/index.tsx
src/components/organisms/Settings/Project/Plugin/hooks.ts
src/components/organisms/Settings/Project/Plugin/index.tsx

chore: add remaining props to plugin settings extensions

---

src/components/molecules/Visualizer/Widget/Timeline/hooks.ts

Fixed bug that timeline speed is not changed

fix: timeline speed bug

---

src/components/molecules/Settings/Project/Plugin/PluginSection/index.tsx

fix: wrapper styles in plugin section for plugin extension

---

src/components/molecules/Common/AssetModal/AssetContainer/index.tsx
src/components/molecules/Common/AssetModal/index.tsx
src/components/molecules/Visualizer/Engine/Cesium/Tileset/index.tsx

fix: 3d tile not updating until source type is selected

---

src/components/atoms/Timeline/ScaleList.tsx
src/components/atoms/Timeline/index.tsx
src/components/organisms/GlobalModal/index.tsx

fix: timeline width exceeding browser width

---

src/components/molecules/Settings/Project/Plugin/PluginSection/index.tsx
src/components/organisms/Settings/Project/Plugin/hooks.ts
src/components/organisms/Settings/Project/Plugin/index.tsx
src/gql/graphql-client-api.tsx
src/gql/queries/plugin.ts

fix: cannot to upgrade marketplace plugins

---

src/components/molecules/Visualizer/Engine/Cesium/Marker/index.tsx

Memo the material, then it display

feat: fix layer(marker) extrdue line disapear 

---

src/components/molecules/Visualizer/Engine/Cesium/core/Imagery.test.ts
src/components/molecules/Visualizer/Engine/Cesium/core/Imagery.tsx
src/components/molecules/Visualizer/Engine/Cesium/core/presets.ts
src/components/molecules/Visualizer/Engine/Cesium/hooks.ts
src/components/molecules/Visualizer/Engine/Cesium/index.tsx
src/components/molecules/Visualizer/Engine/Cesium/terrain.ts
src/components/molecules/Visualizer/Engine/index.tsx
src/components/molecules/Visualizer/Widget/Navigator/NavigatorPresenter/index.tsx
src/components/molecules/Visualizer/index.tsx
src/components/organisms/EarthEditor/CanvasArea/hooks.ts
src/components/organisms/EarthEditor/CanvasArea/index.tsx
src/components/organisms/Published/hooks.ts
src/components/organisms/Published/index.tsx
src/config/index.ts

Cesium Ion default access token can now be set from rearth_config.json.

feat: set Cesium Ion default access token via config

---

src/core/mantle/atoms/compute.test.ts
src/core/mantle/atoms/compute.ts

fix: cache logic for feature

---

src/core/engines/Cesium/index.tsx

I did refactor to narrow the range of feature context in cesium engine component.

refactor: move feature context

---

.storybook/main.ts
package.json
src/core/mantle/data/csv.test.ts
src/core/mantle/data/csv.ts
src/core/mantle/data/index.ts
src/core/mantle/types/index.ts
vite.config.ts
yarn.lock

I've done support for CSV on the reearth/core.

feat: support CSV on reearth/core

---

.storybook/public/testdata/sample.gltf
src/core/engines/Cesium/Feature/Model/index.stories.tsx
src/core/engines/Cesium/Feature/Model/index.tsx
src/core/mantle/types/appearance.ts

I've supported glTF file on the reearth/core.

feat: support glTF on reearth/core

---

.storybook/public/testdata/sample.czml
.storybook/public/testdata/sample.gltf
src/core/engines/Cesium/Feature/Model/index.stories.tsx
src/core/engines/Cesium/Feature/Model/index.tsx
src/core/engines/Cesium/Feature/Resource/index.stories.tsx
src/core/engines/Cesium/Feature/Resource/index.tsx
src/core/engines/Cesium/Feature/index.tsx
src/core/engines/Cesium/Feature/utils.tsx
src/core/engines/Cesium/index.tsx
src/core/engines/index.ts
src/core/mantle/compat/backward.test.ts
src/core/mantle/compat/backward.ts
src/core/mantle/compat/forward.test.ts
src/core/mantle/compat/forward.ts
src/core/mantle/types/appearance.ts
src/core/mantle/types/index.ts

I've supported CZML format in Resource component.
You can check the feature in `/src/core/engines/Cesium/Feature/Resource/index.stories.tsx`.

feat: support CZML in reearth/core

---

src/core/engines/Cesium/Feature/Raster/hooks.ts
src/core/engines/Cesium/Feature/Raster/index.stories.tsx

I fixed MVT to support dynamic update. For example, MVT need to be updated dynamically when style like `fillColor` is updated.
https://user-images.githubusercontent.com/34934510/211709607-e907865c-18ea-426d-bb05-a085df116e90.mp4

fix: update mvt dynamically when appearance is updated

---

src/core/engines/Cesium/Feature/Tileset/hooks.ts
src/core/engines/Cesium/Feature/Tileset/index.stories.tsx
src/core/engines/Cesium/Feature/Tileset/index.tsx
src/core/engines/Cesium/Feature/index.tsx
src/core/mantle/types/appearance.ts

https://user-images.githubusercontent.com/34934510/211709315-2c57943d-f366-4660-a3fd-e755b8d3bb77.mp4

feat: support 3dtiles on reearth/core

---

src/core/Crust/Widgets/Widget/Navigator/NavigatorPresenter/index.tsx
src/core/Crust/Widgets/Widget/Navigator/index.tsx
src/core/engines/Cesium/common.ts
src/core/engines/Cesium/useEngineRef.test.tsx
src/core/engines/Cesium/useEngineRef.ts

I ported a support of navigator in 2d mode that was fixed in https://github.com/reearth/reearth-web/pull/360.

feat: port 2d navigator to reearth/core

---

src/core/Crust/Widgets/Widget/Navigator/NavigatorPresenter/index.tsx
src/core/Crust/Widgets/Widget/Navigator/index.tsx
src/core/Crust/Widgets/Widget/index.tsx
src/core/Visualizer/index.tsx

fix: visualizer on reearth/core

---

src/components/atoms/Plugin/IFrame/hooks.ts

fix: make iframe width or height assignable without the other

---

src/core/Crust/Plugins/Plugin/hooks.ts
src/core/Crust/Plugins/plugin_types.ts
src/core/Crust/Plugins/storybook.tsx
src/core/Crust/Plugins/usePluginInstances.ts

feat: add runTimes property to PluginInstance on reearth/core

---

src/components/molecules/Visualizer/usePluginInstances.ts

fix: plugin instance runTimes property

---

src/components/molecules/Visualizer/Plugin/hooks.ts

fix: increment runTimes on preinit

---

src/components/molecules/Visualizer/WidgetAlignSystem/MobileZone.tsx
src/components/molecules/Visualizer/useWidgetAlignSystem.ts

fix: widget align system on mobile

---

src/core/Crust/Plugins/Plugin/hooks.ts
src/core/Crust/Plugins/Plugin/index.tsx
src/core/Crust/Widgets/WidgetAlignSystem/MobileZone.tsx
src/core/Crust/Widgets/WidgetAlignSystem/Zone.tsx
src/core/Crust/Widgets/WidgetAlignSystem/index.tsx
src/core/Crust/Widgets/index.tsx
src/core/Crust/Widgets/useWidgetAlignSystem.ts

fix: make widget to be invisible when ui is closed

---

src/components/organisms/EarthEditor/core/CanvasArea/convert.ts
src/components/organisms/Published/core/hooks.ts

fix: moveTo widget to empty page on mobile on reearth/core

---

src/core/mantle/data/csv.test.ts
src/core/mantle/data/csv.ts

fix: support csv value string on reearth/core

---

src/core/engines/Cesium/hooks.ts

fix: cannot select features on reearth/core

---

src/core/Crust/Widgets/WidgetAlignSystem/MobileZone.tsx
src/core/Crust/Widgets/WidgetAlignSystem/index.tsx
src/core/Crust/Widgets/WidgetAlignSystem/utils.ts
src/core/Crust/Widgets/useWidgetAlignSystem.ts

- moveTo was not working specific case.
- When we have inner zone, WAS was not working correctly.

fix: WAS bug on reearth/core

---

src/core/engines/Cesium/Feature/index.tsx
src/core/mantle/types/index.ts

feat: support kml on reearth/core

---

src/core/engines/Cesium/Feature/PhotoOverlay/index.tsx
src/core/mantle/compat/forward.test.ts
src/core/mantle/compat/forward.ts

fix: dnd layer on reearth/core

---

src/core/mantle/atoms/compute.test.ts
src/core/mantle/atoms/compute.ts

perf: improve blink when feature is updated on reearth/core

---

src/core/engines/Cesium/Feature/Tileset/hooks.ts
src/core/engines/Cesium/Feature/index.tsx
src/core/engines/Cesium/index.tsx
src/core/mantle/compat/forward.test.ts
src/core/mantle/compat/forward.ts
src/core/mantle/types/appearance.ts
src/core/mantle/types/index.ts

feat: support osm data type on reearth/core

---

src/core/engines/Cesium/Feature/Resource/index.tsx
src/core/engines/Cesium/Feature/index.tsx
src/core/mantle/compat/forward.ts
src/core/mantle/data/index.ts
src/util/path.test.ts
src/util/path.ts

fix: support resource auto on reearth/core

---

src/core/mantle/compat/forward.ts

fix: undefined behavior for resource on reearth/core

---

src/core/Map/Layers/index.tsx

fix: selected layer id is not propagated on reearth/core

---

src/components/organisms/EarthEditor/core/CanvasArea/convert.ts
src/components/organisms/EarthEditor/core/CanvasArea/index.tsx
src/core/Crust/Widgets/Widget/builtin.ts
src/core/Crust/Widgets/Widget/index.tsx
src/core/Visualizer/hooks.ts
src/core/Visualizer/index.tsx

fix: disable requestRenderMode depends on widget on reearth/core

---

src/core/mantle/atoms/compute.test.ts
src/core/mantle/atoms/compute.ts

fix: layer fetch on reearth/core

---

src/components/molecules/Visualizer/Engine/Cesium/index.tsx
src/components/molecules/Visualizer/Engine/ref.ts
src/core/Map/types/index.ts
src/core/engines/Cesium/index.tsx

```
reearth.scene.overrideProperty({default:{vr:true}})
```

feat: scene property to enable VR mode

---

src/core/engines/Cesium/Feature/Box/Edge.tsx
src/core/engines/Cesium/Feature/Box/ScalePoints.tsx
src/core/engines/Cesium/Feature/Box/Side.tsx
src/core/engines/Cesium/Feature/Box/hooks/box.ts
src/core/engines/Cesium/Feature/Box/index.tsx
src/core/engines/Cesium/Feature/Ellipsoid/index.tsx
src/core/engines/Cesium/Feature/Marker/index.tsx
src/core/engines/Cesium/Feature/Model/index.tsx
src/core/engines/Cesium/Feature/PhotoOverlay/index.tsx
src/core/engines/Cesium/Feature/Polygon/index.tsx
src/core/engines/Cesium/Feature/Polyline/index.tsx
src/core/engines/Cesium/Feature/utils.tsx
src/core/mantle/evaluator/simple/index.ts
src/core/mantle/evaluator/simple/interval.test.ts
src/core/mantle/evaluator/simple/interval.ts
src/core/mantle/types/index.ts

I supported interval data format.
You can test by the following script.
```js
data: {
type: "csv",
url: "/sample.csv",
time: {
property: "time",
interval: 10000000,
},
csv: {
idColumn: "id",
latColumn: "latitude",
lngColumn: "longitude",
noHeader: false,
}
},
marker: {
imageColor: {
expression: "${name} === 'hoge' ? color('blue') : color('red')",
}
}
});
reearth.scene.overrideProperty({ timeline: { visible: true } });
```
https://user-images.githubusercontent.com/34934510/217768668-90e80094-536a-4630-9dd0-ab97c71f81f9.mov

feat: support time series features on reearth/core

---

src/components/molecules/Visualizer/Widget/Timeline/hooks.ts
src/components/molecules/Visualizer/Widget/Timeline/index.tsx
src/core/Crust/Widgets/Widget/Timeline/hooks.ts
src/core/Crust/Widgets/Widget/Timeline/index.tsx
src/core/Crust/Widgets/WidgetAlignSystem/Area.tsx
src/core/Crust/Widgets/WidgetAlignSystem/types.ts
src/core/Crust/Widgets/index.tsx

fix: expand timeline in initial load

---

src/core/mantle/compat/forward.ts

fix: error in published page on reearth/core

---

src/components/pages/EarthEditor/index.tsx
src/components/pages/Preview/index.tsx
src/components/pages/Published/index.tsx
src/util/use-core.ts

feat: use experimental core flag

---

src/core/Map/Layer/hooks.ts
src/core/mantle/atoms/compute.test.ts
src/core/mantle/atoms/compute.ts
src/core/mantle/atoms/data.ts
src/core/mantle/types/index.ts

I tested with the following vite custom server plugin.
<details>
<summary>plugin</summary>
<pre>
let cnt = 0;
function geojson(): Plugin {
return {
name: "reearth-geojson",
async configureServer(server) {
server.middlewares.use((req, res, next) => {
if (req.method === "GET" && req.url === "/sample.geojson") {
const configRes = (() => {
if (cnt % 2 === 0) {
return JSON.stringify(
{
type: "FeatureCollection",
features: [
{
type: "Feature",
geometry: {
type: "Point",
coordinates: [-47.18951431751117, -24.789938520384457],
},
properties: {},
},
{
type: "Feature",
geometry: {
type: "Point",
coordinates: [155.84221983372979, 74.01264716547318],
},
properties: {},
},
{
type: "Feature",
geometry: {
type: "Point",
coordinates: [110.07076785868927, -89.46999216488513],
},
properties: {},
},
{
type: …

feat: support interval fetching data on reearth/core

---

src/core/Crust/Plugins/hooks.ts
src/core/Crust/Plugins/plugin_types.ts
src/core/engines/Cesium/hooks.ts

- Added featureId to select event as second args.
- Fixed infinite calling select event

fix: select event behavior on reearth/core

---

src/core/engines/Cesium/hooks.ts

fix: select entity on reearth/core

---

src/core/Crust/Widgets/Widget/Button/MenuButton.tsx
src/core/Crust/Widgets/Widget/Button/index.tsx
src/core/Crust/Widgets/Widget/Navigator/hooks.ts
src/core/Crust/Widgets/Widget/Navigator/index.tsx
src/core/Crust/Widgets/Widget/SplashScreen/index.tsx
src/core/Crust/Widgets/Widget/Timeline/hooks.ts
src/core/Crust/Widgets/Widget/Timeline/index.tsx
src/core/Crust/Widgets/Widget/index.tsx
src/core/Crust/Widgets/Widget/useVisible.ts
src/core/Crust/Widgets/index.tsx

feat: use visible field on reearth/core

---

src/core/Crust/Widgets/Widget/Navigator/hooks.ts
src/core/Crust/Widgets/Widget/Timeline/hooks.ts

fix: undefined behavior for visible field

---

src/core/Crust/Widgets/Widget/useVisible.ts

fix: express undefined visible field on reearth/core

---

src/components/atoms/Timeline/index.tsx
src/core/Crust/Widgets/Widget/Timeline/hooks.ts
src/core/Crust/Widgets/Widget/Timeline/index.tsx

feat: support timeline on mobile on reearth/core

---

src/core/Crust/Plugins/PluginFrame/hooks.ts
src/core/Crust/Plugins/api.ts
src/core/Crust/Plugins/hooks.ts
src/core/Crust/Plugins/plugin_types.ts
src/core/Crust/Plugins/storybook.tsx
src/core/Map/ref.ts
src/core/Map/types/index.ts
src/core/engines/Cesium/useEngineRef.ts

feat: add sampleTerrainHeight on reearht/core

---

src/core/engines/Cesium/Feature/Tileset/hooks.ts
src/core/mantle/types/value.ts

feat: support clipping box direction on reearth/core

---

src/core/mantle/data/csv.test.ts
src/core/mantle/data/csv.ts

fix: coordinates for csv on reearth/core

---

package.json
src/components/atoms/Plugin/hooks.ts
src/core/Crust/Plugins/PluginFrame/hooks.ts
yarn.lock

fix: errors when many functions are created in plugins

---

src/core/mantle/evaluator/simple/expression/node.ts
src/core/mantle/evaluator/simple/index.test.ts

fix: color function on reearth/core

---

src/core/Crust/Plugins/api.ts
src/core/Crust/Plugins/hooks.ts
src/core/Crust/Plugins/plugin_types.ts
src/core/Map/Layers/hooks.test.ts
src/core/Map/Layers/hooks.ts

fix: overridden layers api on reearth/core

---

src/core/mantle/evaluator/simple/interval.ts

fix: error handling for time interval on reearth/core

---

src/core/Map/Layers/hooks.test.ts
src/core/Map/Layers/hooks.ts
src/core/Map/Layers/utils.test.ts
src/core/Map/Layers/utils.ts

fix: layers override behavior on rearth/core

---

src/core/Visualizer/hooks.ts
src/core/engines/Cesium/hooks.ts

fix: infobox property is undefined error on reearth/core

---

src/core/engines/Cesium/Feature/index.tsx

fix: entity id is duplicated error on reearth/core

---

src/core/Map/Layer/hooks.ts

fix: force update when some data properties are updated on reearth/core

---

src/core/Map/Layers/hooks.test.ts
src/core/Map/Layers/hooks.ts

fix: delete bug that deletes necessary layer on reearth/core

---

src/core/engines/Cesium/Feature/Resource/index.tsx
src/core/engines/Cesium/hooks.ts
src/core/engines/Cesium/useEngineRef.ts
src/core/engines/Cesium/utils.ts

- Attach layerId to Resource appearance.
- Support flyTo for DataSource

feat: support resource entity layerId on reearth/core

---

src/core/engines/Cesium/Feature/Polygon/index.tsx
src/core/engines/Cesium/Feature/Resource/utils.ts
src/core/mantle/types/appearance.ts

feat: extrudedHeight for polygon on reearth/core

---

src/components/molecules/Visualizer/Engine/Cesium/Box/utils.ts
src/core/engines/Cesium/Feature/Box/hooks/box.ts
src/core/engines/Cesium/Feature/Box/index.tsx
src/core/engines/Cesium/Feature/Tileset/hooks.ts
src/core/engines/Cesium/Feature/Tileset/index.tsx
src/core/engines/Cesium/Feature/Tileset/useClippingBox.ts
src/core/engines/Cesium/common.ts
src/core/mantle/types/value.ts

feat: add builtin clipping box on reearth/core

---

src/core/Map/Layer/hooks.ts

perf: improve expression cache strategy on reearth/core

---

src/core/engines/Cesium/Feature/Tileset/hooks.ts

perf: improve 3dtiles features calculation on reearth/core

---

src/core/engines/Cesium/Feature/Tileset/hooks.ts

perf: improve skipping computing process for 3dtiles on reearth/core

---

src/core/Map/Layers/hooks.ts
src/core/Visualizer/hooks.ts

Fix getting infobox from undefined.

fix: infobox error after layer delete

---

src/core/mantle/data/gpx.test.ts
src/core/mantle/data/gpx.ts

BUG fix for the feature type in gpx data format.

fix: feature type fix gpx on reearth/core

---

src/core/engines/Cesium/Feature/Tileset/index.tsx
src/core/engines/Cesium/common.ts
src/core/mantle/types/appearance.ts

feat: color blend mode in tileset on reearth/core

---

src/core/engines/Cesium/Feature/Raster/hooks.ts

fix: mvt cache on reearth/core

---

src/core/Map/index.tsx
src/core/engines/Cesium/Feature/Tileset/hooks.ts
src/core/engines/Cesium/Feature/Tileset/index.tsx
src/core/engines/Cesium/Feature/Tileset/useClippingBox.ts

I fixed a bug that clip area doesn't match with box area.

fix: clip area with clipping box on reearth/core

---

src/core/engines/Cesium/Feature/Tileset/hooks.ts
src/core/engines/Cesium/utils.ts

perf: compute features concurrently on reearth/core

---

src/core/engines/Cesium/Feature/Box/hooks/box.ts
src/core/engines/Cesium/Feature/Box/index.tsx
src/core/engines/Cesium/Feature/Tileset/hooks.ts
src/core/engines/Cesium/Feature/Tileset/index.tsx
src/core/engines/Cesium/Feature/Tileset/useClippingBox.ts
src/core/mantle/types/value.ts

fix: allow enter ground option for clipping box on reearth/core

---

package.json
src/core/engines/Cesium/Feature/Raster/hooks.ts
yarn.lock

perf: improve mvt rendering on reearth/core

---

package.json
yarn.lock

feat: update cesium

---

package.json
yarn.lock

fix: mvt line width on reearth/core

---

src/components/molecules/PluginEditor/core/hooks.ts
src/components/molecules/PluginEditor/core/index.tsx
src/components/molecules/PluginEditor/hooks.ts
src/components/molecules/PluginEditor/index.tsx

fix: pass engine meta on plugin editor

---

src/core/mantle/evaluator/simple/expression/runtime.ts
src/core/mantle/evaluator/simple/expression/variableReplacer.test.ts
src/core/mantle/evaluator/simple/expression/variableReplacer.ts
src/core/mantle/evaluator/simple/index.test.ts

fix: parse reserved word when property name includes reserved word on reearth/core

---

src/components/molecules/Visualizer/Engine/Cesium/Marker/index.tsx
src/core/engines/Cesium/Feature/Marker/index.tsx
src/core/mantle/types/appearance.ts

feat: imageSizeInMeters field in marker proeperty

---

src/core/engines/Cesium/Feature/Resource/index.tsx

fix: selecting resource feature behavior on reearth/core

---

src/core/engines/Cesium/Feature/Resource/utils.ts

fix: infinite infobox in CZML on reearth/core

---

src/core/engines/Cesium/Feature/Resource/index.tsx

fix: attach style dynamically in resource on reearth/core

---

src/core/Map/Layers/utils.ts

fix: copying lazy layers undefined behavior on reearth/core

---

src/core/Map/Layers/utils.ts

perf: copy lazy layer lazily

---

src/core/Crust/Plugins/api.ts
src/core/Map/Layers/index.tsx
src/core/Map/Layers/utils.ts
src/core/Map/index.tsx

fix: remove copyLazyLayer on reearth/core

---

src/core/engines/Cesium/Feature/Raster/hooks.ts
src/core/mantle/types/index.ts

sample
```js
data: { 
type: "wms",
url: "https://example.com/wms",
layers: "layerName",
parameters: {
transparent: "true",
format: "image/png"
}
},
});
```

feat: add parameters property to data on reearth/core

---

src/core/engines/Cesium/Feature/Raster/hooks.ts

perf: stop synchronizing features in MVT on reearth/core

---

src/core/engines/Cesium/Feature/Ellipsoid/index.tsx
src/core/engines/Cesium/Feature/Marker/index.tsx
src/core/engines/Cesium/Feature/Model/index.tsx
src/core/engines/Cesium/Feature/PhotoOverlay/index.tsx
src/core/engines/Cesium/Feature/Polygon/index.tsx
src/core/engines/Cesium/Feature/Polyline/index.tsx
src/core/engines/Cesium/hooks.ts

fix: use default block for entity on reearth/core

---

src/core/engines/Cesium/Feature/Resource/utils.test.ts
src/core/engines/Cesium/Feature/Resource/utils.ts
src/core/mantle/evaluator/simple/index.ts

I fixed to handle marker style in CZML.
Also I fixed the problem that application is crashed when evaluator fails.

fix: czml style for marker on reearth/core

---

src/core/engines/Cesium/Feature/Resource/utils.ts

fix: condition for CZML on reearth/core

---

src/core/Crust/Widgets/Widget/Timeline/hooks.ts

I fixed some error on timeline widget.
- Fixed error that start or stop or current time overs real time then Cesium throw error.
- Fixed timeline behavior to accord with Cesium timeline

fix: timeline behavior on reearth/core

---

src/core/Crust/Widgets/Widget/Timeline/hooks.ts
src/core/engines/Cesium/Feature/Resource/utils.ts

fix: some error on reearth/core

---

src/core/Crust/Widgets/Widget/Timeline/hooks.ts

fix: timeline bug on reearth/core

---

src/core/mantle/evaluator/simple/expression/variableReplacer.ts

perf: improve regexp on reearth/core

---

src/core/Map/Layer/hooks.ts

I've added a polyfill for requestIdleCallback to reearth/core to make sure the layer deletion works in iOS too.
Note: requestIdleCallback is still experimental for iOS.

fix: add polyfill for requestIdleCallback in reearth/core

---

src/core/engines/Cesium/useEngineRef.ts

fix: fly to multiple entities added by a layer on reearth/core

---

src/core/Map/Layer/hooks.ts

fix: trigger select event when featureId is changed on reearth/core

---

src/core/engines/Cesium/utils.ts

fix: use attributes as default content for infobox on reearth/core

---

src/core/engines/Cesium/Feature/Tileset/hooks.ts
src/core/engines/Cesium/Feature/utils.tsx
src/core/engines/Cesium/hooks.ts
src/core/engines/Cesium/types.ts
src/core/engines/Cesium/useEngineRef.ts
src/core/engines/Cesium/utils.ts
src/core/mantle/types/appearance.ts

feat: support styling for point cloud on reearth/core

---

src/core/engines/Cesium/Feature/Tileset/hooks.ts
src/core/engines/Cesium/Feature/Tileset/useClippingBox.ts

fix: clipping box on point cloud on reearth/core

---

src/core/engines/Cesium/Feature/Raster/hooks.ts
src/core/engines/Cesium/Feature/utils.tsx
src/core/engines/Cesium/hooks.ts
src/core/engines/Cesium/utils.ts

fix: support default infobox and selection indicator on imagery layer on reearth/core

---

src/core/engines/Cesium/Feature/Resource/utils.ts

fix: use computed feature on resource on reearth/core

---

package.json
yarn.lock

fix: support multi layers in MVT on reearth/core

---

src/core/Map/Layers/hooks.ts

fix: sync selected feature with layer api on reearth/core

---

src/core/mantle/evaluator/simple/expression/variableReplacer.ts

fix: JSON Path condition on reearth/core

---

package.json
src/core/engines/Cesium/Feature/Raster/hooks.ts
src/core/mantle/evaluator/simple/expression/expression.test.ts
src/core/mantle/evaluator/simple/expression/expression.ts
src/core/mantle/evaluator/simple/expression/runtime.ts
src/core/mantle/evaluator/simple/expression/variableReplacer.test.ts
src/core/mantle/evaluator/simple/expression/variableReplacer.ts
yarn.lock

I did three things to improve performance.
1. Cache MVT tile in MVT lib.
2. Cache evaluated style in Raster component
3. Cache replacedVariable without JSONPath.

perf: improve styling in MVT on reearth/core

---

package.json
yarn.lock

feat: upgrade mvt lib

---

src/core/engines/Cesium/Feature/Raster/hooks.ts

fix: MVT isn't render correctly on reearth/core

---

src/core/Crust/Plugins/PluginFrame/IFrame/hooks.ts

fix: can't set iframe's width or height individually in crust 

---

src/core/engines/Cesium/Feature/index.tsx

fix: use layer id with feature id for entity id on reearth/core

---

package.json
yarn.lock

feat: upgrade cesium-mvt-imagery-provider

---

src/core/engines/Cesium/Feature/Raster/hooks.ts
src/core/engines/Cesium/hooks.ts

fix: prevent selecting not shown feature for MVT on reearth/core

---

src/core/engines/Cesium/Feature/index.tsx

This PR removes duplication of entity of feature in cesium with the help a set.

fix: remove duplication of feature entity in reearth/core

---

src/core/Crust/Plugins/Plugin/hooks.ts
src/core/Crust/Plugins/Plugin/index.tsx

fix: rename moveWidget to onMoveWidget on reearth/core

---

package.json
src/core/engines/Cesium/Feature/Raster/index.tsx
src/core/engines/Cesium/Feature/Raster/mvt.ts
yarn.lock

[Implementation detail is here.](https://github.com/reearth/cesium-mvt-imagery-provider/pull/3)
|Polyline|Point|
|:--:|:--:|
|![Screenshot 2023-04-10 at 19 14 33](https://user-images.githubusercontent.com/34934510/230883605-5ebbbc25-ebd5-4e70-9c5f-1ba676838b10.png)|![Screenshot 2023-04-10 at 19 15 44](https://user-images.githubusercontent.com/34934510/230883662-ace3738e-eecb-4080-a81e-6b973bdf3ee8.png)|

feat: support polyline and point on reearth/core

---

src/components/organisms/Authentication/RootPage/hooks.ts
src/components/organisms/Dashboard/hooks.ts
src/components/organisms/EarthEditor/Header/hooks.ts
src/components/organisms/EarthEditor/Header/index.tsx
src/components/organisms/EarthEditor/PropertyPane/hooks.ts
src/components/organisms/EarthEditor/PropertyPane/index.tsx
src/components/organisms/Settings/Account/hooks.ts
src/components/organisms/Settings/Account/index.tsx
src/components/organisms/Settings/Project/Dataset/hooks.ts
src/components/organisms/Settings/Project/Dataset/index.tsx
src/components/organisms/Settings/Project/Public/hooks.ts
src/components/organisms/Settings/Project/Public/index.tsx
src/components/organisms/Settings/Project/hooks.ts
src/components/organisms/Settings/Project/index.tsx
src/components/organisms/Settings/ProjectList/hooks.ts
src/components/organisms/Settings/SettingPage/hooks.ts
src/components/organisms/Settings/SettingPage/index.tsx
src/components/organisms/Settings/Workspace/Asset/hooks.ts
src/components/organisms/Settings/Workspace/Asset/index.tsx
src/components/organisms/Settings/Workspace/hooks.ts
src/components/organisms/Settings/Workspace/index.tsx
src/components/organisms/Settings/WorkspaceList/index.tsx
src/components/pages/Authentication/hooks.ts
src/state/index.ts

Replace the Team in code that is related to the team state  to be workspace

refactor: replace "team" word  related to Team state with "workspace"
